### ISSUE TITLE
how do you even use this

### ISSUE THREAD

**Issue by fluttershy0471** [Darkened5ky/Wind-Waker-Item-and-Map-Tracker#1]
im used to trackers with an .exe format and theres nothing that opens the tracker as far as im aware of.
or what file do you need to open the tracker.

**Comment by pkmnfrk** [comment]
Strange that it doesn't say anywhere, but you use it with EmoTracker (https://emotracker.net/)

**Comment by Darkened5ky** [comment]
Yes, you need to use EmoTracker (see above). I'm sorry I forgot to specify this, I'll be adding that to the readme
