### ISSUE TITLE
Forbidden Fortress Chest Upper Jail Cell

### ISSUE THREAD

**Issue by Kiieewiiee** [Darkened5ky/Wind-Waker-Item-and-Map-Tracker#14]
This Chest is unavailable until you get an item to get over to that platform like the hookshot or the leaf. Yet the Chest can be reached by simply being taken by a floormaster, and being thrown into the Cell. I'd suspect that the forbidden fortress text is yellow (possible to be reached) via a glitch so that shouldn't be a problem.

**Comment by DualVission** [comment]
I cannot close issue requests directly, but the tracker can technically already do that. There are a lot of tricks that were already built-in.
