### ISSUE TITLE
Tracking logic issues

### ISSUE THREAD

**Issue by GriffinG1** [Darkened5ky/Wind-Waker-Item-and-Map-Tracker#7]
Hey! Noticed something wrong with some of the tracking logic.

In TOTG, `Big Key Chest` and `Gohdan Heart Container` are both marked as impossible without the leaf. This isn't accurate, as you can jump onto the statues on the side where you need the leaf (in the 3rd idol room), then jump slash over the beams blocking the idol. Therefore, they're glitch access instead of impossible.

A quick glance around can't find documentation of this, but I just did it myself and it's rather easy to do. Likely not documented due to a lack of use outside of randomizers?

Also, in Angular Isles, `Light Puzzle` seems to be deku leaf locked too, despite it being fully completable with the hookshot...

**Comment by GriffinG1** [comment]
Further investigation has shown that the Angular Isles one was a result of #6...
![image](https://user-images.githubusercontent.com/28538707/90599394-04d94e80-e1b2-11ea-940e-1ece367cdd4b.png)

And the TOTG one was a result of commit cb5c7ae, where it was removed, then skipped over when sequence breaks were fixed in EmoTracker.

**Comment by cheuer** [comment]
Both of these should be fixed by v2.0.2.0 now, please let us know if there's still an issue after updating.
